### ISSUE TITLE
Implement visual regression testing

### ISSUE THREAD

**Issue by mzdr** [gridonic/sass#2]
In projects where we can heavily rely on a component-based development, visual regression testing would save us a lot of time especially when it comes to unintended changes/bugs related to refactoring.

~~See [PhantomCSS](https://github.com/Huddle/PhantomCSS) for details.~~ A simple test case (success and fail) should be provided.

**Comment by mzdr** [comment]
[Gemini](https://github.com/gemini-testing/gemini) it is.

**Comment by peschee** [comment]
@mzdr Running tests with `yarn test -- --root-url http://gridonic-sass.dev/styleguide/`

fails with

```
$ ./bin/gemini test --root-url http://gridonic-sass.dev/styleguide/
 Selenium  selenium-standalone start 2> /dev/null exited with code 1
--> Sending SIGTERM to other processes..
 Gemini  wait-on tcp:4444 && gemini --config ./gemini/config.yml --reporter flat test exited with code null
error Command failed with exit code 1.
```

Any ideas what's missing? Styeguide is available at http://gridonic-sass.dev/styleguide/

**Comment by mzdr** [comment]
@peschee I don’t really get what’s actually making trouble over here – as I’m not a Bash guru – but I guess it’s a combination of NPM quoting additional parameters and how `$@` works. With `$*` it should work, just tested in on my machine.

I also don’t know if that’s a bad change since [Googles Shell Style Guide](https://google.github.io/styleguide/shell.xml) says:

> Use "$@" unless you have a specific reason to use $*.

Maybe this is a specific reason? ¯\\\_(ツ)\_/¯
